version: "3"
virtualmachines:
- name: workstation
  image: instruqt-kula/sgt-rsync-workstation-1775072433
  shell: /bin/bash
  memory: 4096
  cpus: 1
- name: fileserver
  image: instruqt-kula/sgt-rsync-fileserver-1775072434
  shell: /bin/bash
  memory: 4096
  cpus: 1
virtualbrowsers:
- name: rsync-docs
  url: https://download.samba.org/pub/rsync/rsync.1
