#!/bin/bash

set -euxo pipefail

DATA_REPO_ORIGIN="instruqtkula/vosp_1000"

function setup_fail () {
    echo "##### SETUP FAIL #####" "$@"
    exit 1
}

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the virtual machine"
    sleep 5
done


echo "Install ssh key from track custom resource"
pushd /home/iggy/.ssh
echo "${IGGYS_KEY_SSH_PRIVATE_KEY_BASE64}" | base64 -d > id_ed25519
echo "${IGGYS_KEY_SSH_PUBLIC_KEY}" > id_ed25519.pub
cp id_ed25519.pub authorized_keys
chown iggy:iggy id_ed25519* authorized_keys
chmod 400 id_ed25519* authorized_keys
popd

echo "Setup done"
exit 0
