#!/bin/bash
# Copyright (C) 2026, Instruqt. All Rights Reserved.

set -euxo pipefail

function setup_fail () {
    echo "##### SETUP FAIL #####" "$@"
    exit 1
}


# In this track the first challenge will be to download the
# data from the fileserver to the workstation. Later challenges
# will show various features of rsync by copying data around
# locally on the workstation. Finally, the participant will
# upload some data to the fileserver.
#
# On the fileserver we create and pre-populate the data in
# /opt/data.
#
# On both hosts we also put a copy in /root/data, for use
# by check scripts as a known-clean source of the original
# data.
#
# By the time we get to this script, our packer configuration
# has placed a .tgz file of the data in /tmp/vosp_1000.tgz

# Clean data on both hosts. 
sudo install -o root -g root -m 700 -d /root/data || setup_fail "Unable to create '/root/data'"
sudo tar -C /root/data -xf /tmp/vosp_1000.tgz || setup_fail "Unpacking data in '/root/data'"
sudo chgrp -R data /root/data/vosp_1000

# Also pre-populate the data in /opt/data, but only on the fileserver
if [ "${DESTINATION_HOST}" == "fileserver" ]; then
    sudo install -o root -g data -m 2770 -d /opt/data || setup_fail "Unable to create '/opt/data/'"
    sudo tar -C /opt/data -xf /tmp/vosp_1000.tgz || setup_fail "Unpacking data in '/opt/data'"
    sudo chgrp -R data /opt/data/vosp_1000
fi
