#!/bin/bash

set -euxo pipefail


# Is there even the expected target directory?

if [ ! -d /home/iggy/vosp_1000 ]; then
    fail-message "The 'vosp_1000' directory doesn't exist. Did you run the 'rsync' command?"
    exit 1
fi

# Mimic the command iggy should have ran, but in a temporary
# directory so we can do a file comparision

TESTDIR=$(mktemp -d)
chown iggy:iggy "${TESTDIR}"

pushd "${TESTDIR}"

# We run *every* command we tell iggy to run

sudo -u iggy rsync -av --stats --include '*.lbl' fileserver:/opt/data/vosp_1000/ vosp_1000/
sudo -u iggy rm -rf vosp_1000/
sudo -u iggy rsync -av --stats --exclude '*' fileserver:/opt/data/vosp_1000/ vosp_1000/
sudo -u iggy rsync -av --stats --exclude '*' --include '*.lbl' fileserver:/opt/data/vosp_1000/ vosp_1000/
sudo -u iggy rsync -av --stats --include '*.lbl' --exclude '*' fileserver:/opt/data/vosp_1000/ vosp_1000/
sudo -u iggy rsync -av --stats --include '*.lbl' --include '*/' --exclude '*' fileserver:/opt/data/vosp_1000/ vosp_1000/


# Now use three rsync options to verify that the directories are identical
#   --dry-run         - don't actually do anything which would touch a file, but-
#   --itemize-changes - print out an itemized list of changes being made to each file
#   --delete          - delete any file in the destination not at the source
#
# If we do that and get no output, the two directories are identical. If you do not
# use the `--delete` option if you have, say, an empty source directory, or files
# missing in the source, then `--itemize-changes` won't show anything because by
# default rsync doesn't delete files.

ITEMIZED=$(mktemp)

# shellcheck disable=SC2024
sudo -u iggy rsync -a \
    --dry-run \
    --itemize-changes \
    --delete \
    vosp_1000/ \
    /home/iggy/vosp_1000/ > "${ITEMIZED}"

if [ -s "${ITEMIZED}" ]; then
    fail-message "That doesn't quite look right, did you run the rsync command with the correct options?"
    exit 1
fi
popd

# If we got here, we're good, cleanup
rm -rf "${TESTDIR}"
rm -f "${ITEMIZED}"

exit 0
