#!/bin/bash

set -euxo pipefail

# In this challenge we are going to demonstrate incremental updates
# We'll do this by copying the files from the fileserver, then deleting
# every file which ends in `.cat`. 

pushd /home/iggy
sudo -u iggy rsync -av --progress --stats fileserver:/opt/data/vosp_1000/ vosp_1000/
find vosp_1000/ -type f -name '*.cat' -exec rm -f '{}' ';'
popd
